server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
            
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**